"""add unique contraint to merchants

Revision ID: cd75a5079cf1
Revises: 03e241eca291
Create Date: 2026-02-18 12:20:16.076160

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd75a5079cf1"
down_revision: Union[str, Sequence[str], None] = "03e241eca291"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_merchants_name"), "merchants", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_merchants_name"), "merchants", type_="unique")
    # ### end Alembic commands ###
