"""add idempotency_key to transactions

Revision ID: db8be2534ef6
Revises: cd75a5079cf1
Create Date: 2026-02-23 15:02:54.973726

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db8be2534ef6"
down_revision: Union[str, Sequence[str], None] = "cd75a5079cf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("idempotency_key", sa.UUID(), nullable=False)
    )
    op.create_unique_constraint(
        op.f("uq_transactions_idempotency_key"), "transactions", ["idempotency_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_transactions_idempotency_key"), "transactions", type_="unique"
    )
    op.drop_column("transactions", "idempotency_key")
    # ### end Alembic commands ###
